import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { WorkspaceManager } from '../src/workspace.mjs';
import { runCommand } from '../src/process.mjs';

test('worktree isolation and patch failures preserve source files and index', async (t) => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'uagc-workspace-'));
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  const repo = path.join(root, 'repo');
  await fs.mkdir(repo);
  const git = async (cwd, ...args) => {
    const r = await runCommand('git', args, { cwd });
    assert.equal(r.code, 0, r.stderr);
    return r.stdout;
  };
  const manager = new WorkspaceManager(path.join(root, 'state'));
  await assert.rejects(manager.prepare(repo, 'worktree', 'test'), /requires a Git/);
  assert.equal((await manager.prepare(repo, 'shared', 'test')).mode, 'shared');
  await git(repo, 'init');
  await git(repo, 'config', 'core.autocrlf', 'false');
  await git(repo, 'config', 'user.name', 'Test');
  await git(repo, 'config', 'user.email', 'test@example.invalid');
  await fs.writeFile(path.join(repo, 'a.txt'), 'base\n');
  await fs.writeFile(path.join(repo, 'b.txt'), 'base\n');
  await git(repo, 'add', '.');
  await git(repo, 'commit', '-m', 'baseline');
  await fs.writeFile(path.join(repo, 'dirty.txt'), 'local');
  await assert.rejects(manager.prepare(repo, 'worktree', 'test'), /clean source/);
  await fs.unlink(path.join(repo, 'dirty.txt'));
  const workspace = await manager.prepare(repo, 'worktree', 'test');
  await fs.writeFile(path.join(workspace.workspaceCwd, 'a.txt'), 'worker\n');
  await git(workspace.workspaceCwd, 'add', '.');
  await git(workspace.workspaceCwd, 'commit', '-m', 'worker committed');
  const patchFile = path.join(root, 'patch');
  const job = { workspace, patchFile };
  const captured = await manager.capture(job);
  assert.deepEqual(captured.changedFiles, ['a.txt']);
  assert.match(captured.patch, /worker/);
  await fs.writeFile(patchFile, captured.patch);
  await fs.writeFile(path.join(repo, 'b.txt'), 'staged user\n');
  await git(repo, 'add', 'b.txt');
  const indexBefore = await git(repo, 'diff', '--cached');
  await assert.rejects(manager.apply(job, { allowDirty: true }), /no longer supported/);
  await assert.rejects(manager.apply(job), /local changes/);
  assert.equal(await git(repo, 'diff', '--cached'), indexBefore);
  await git(repo, 'commit', '-m', 'user changes');
  await fs.writeFile(path.join(repo, 'a.txt'), 'conflicting target\n');
  await git(repo, 'add', '.');
  await git(repo, 'commit', '-m', 'conflict');
  await assert.rejects(manager.apply(job), /branch or HEAD changed/);
  const fresh = await manager.prepare(repo, 'worktree', 'conflict-test');
  const freshJob = { workspace: fresh, patchFile };
  await assert.rejects(manager.apply(freshJob), /git apply/);
  assert.equal(await fs.readFile(path.join(repo, 'a.txt'), 'utf8'), 'conflicting target\n');
  assert.equal(await git(repo, 'status', '--porcelain'), '');
  await fs.writeFile(patchFile, '');
  assert.equal((await manager.apply(freshJob)).applied, false);
  await manager.cleanup(freshJob);
  await git(repo, 'worktree', 'lock', workspace.worktreePath);
  await assert.rejects(manager.cleanup(job), /git worktree/);
  assert.equal((await fs.stat(workspace.worktreePath)).isDirectory(), true);
  await git(repo, 'worktree', 'unlock', workspace.worktreePath);
  assert.equal((await manager.cleanup(job)).cleaned, true);
});
